// SPDX-License-Identifier: AGPL-3.0-only

// Command registrygen deterministically produces Golem's embedded protocol
// 767 registry fixtures from pinned repository inputs.
package main

import (
	"bytes"
	"compress/gzip"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"time"
)

var fixtures = map[string]string{
	"blocks_1.21.1.json":       "BlockFixtureSHA256",
	"entities_1.21.1.json":     "EntityFixtureSHA256",
	"items_1.21.1.json":        "ItemFixtureSHA256",
	"login_packet_1.21.1.json": "FixtureSHA256",
}

func main() {
	check := flag.Bool("check", false, "fail when committed generated data is stale")
	source := flag.String("source", "testdata/registry", "directory containing pinned JSON inputs")
	output := flag.String("output", "internal/registry/data", "generated output directory")
	flag.Parse()
	if err := run(*source, *output, *check); err != nil {
		fmt.Fprintln(os.Stderr, "registrygen:", err)
		os.Exit(1)
	}
}

func run(source, output string, check bool) error {
	names := make([]string, 0, len(fixtures))
	for name := range fixtures {
		names = append(names, name)
	}
	sort.Strings(names)
	checksums := make(map[string]string, len(names))
	generated := make(map[string][]byte, len(names)+1)
	for _, name := range names {
		data, err := os.ReadFile(filepath.Join(source, name))
		if err != nil {
			return fmt.Errorf("read %s: %w", name, err)
		}
		digest := sha256.Sum256(data)
		checksums[fixtures[name]] = fmt.Sprintf("%x", digest)
		compressed, err := deterministicGzip(data)
		if err != nil {
			return fmt.Errorf("compress %s: %w", name, err)
		}
		generated[filepath.Join(output, name+".gz")] = compressed
	}
	generated[filepath.Join(filepath.Dir(output), "manifest_generated.go")] = manifest(checksums)
	if check {
		for path, expected := range generated {
			actual, err := os.ReadFile(path)
			if err != nil {
				return fmt.Errorf("read generated %s: %w", path, err)
			}
			if !bytes.Equal(actual, expected) {
				return fmt.Errorf("generated %s is stale; run make generate", path)
			}
		}
		return nil
	}
	if err := os.MkdirAll(output, 0o755); err != nil {
		return err
	}
	for path, data := range generated {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", path, err)
		}
	}
	return nil
}

func deterministicGzip(data []byte) ([]byte, error) {
	var output bytes.Buffer
	writer, err := gzip.NewWriterLevel(&output, gzip.BestCompression)
	if err != nil {
		return nil, err
	}
	writer.Header.ModTime = time.Unix(0, 0)
	writer.Header.OS = 255
	if _, err := writer.Write(data); err != nil {
		return nil, err
	}
	if err := writer.Close(); err != nil {
		return nil, err
	}
	return output.Bytes(), nil
}

func manifest(checksums map[string]string) []byte {
	names := make([]string, 0, len(checksums))
	for name := range checksums {
		names = append(names, name)
	}
	sort.Strings(names)
	var output bytes.Buffer
	fmt.Fprintln(&output, "// Code generated by tools/registrygen. DO NOT EDIT.")
	fmt.Fprintln(&output, "// SPDX-License-Identifier: AGPL-3.0-only")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "package registry")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "const (")
	for _, name := range names {
		fmt.Fprintf(&output, "\t%s = %q\n", name, checksums[name])
	}
	fmt.Fprintln(&output, ")")
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(fmt.Sprintf("format generated manifest: %v", err))
	}
	return formatted
}
